### ISSUE TITLE
Could not load file or assembly 'System.Drawing.Common'

### ISSUE THREAD

**Issue by Glowstudent777** [kokolihapihvi/RockSnifferLib#10]
Getting this error when running my project. Tried installing 'System.Drawing.Common' with the nuget package manager but still recieve the error.

```bash
Could not load file or assembly 'System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at RockSnifferLib.RSHelpers.PSARCUtil.ReadPSARCHeaderData(FileInfo fileInfo)
   at RockSnifferLib.Sniffing.Sniffer.ProcessPsarcFile(String psarcFile) in C:\pathToProject\RockSnifferLib\Sniffing\Sniffer.cs:line 387
```

**Comment by kokolihapihvi** [comment]
Hi.

Where are you running into this, what are you trying to do?
It looks like the project is using version 6.0.0, your IDE should restore all dependencies automatically, if not, you can try the [dotnet restore command](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore).
There is probably something wrong with your solution/project configuration.

**Comment by Glowstudent777** [comment]
I found the problem. I had the .dll file linked but not the actual projects.
