### ISSUE TITLE
[MacOS port] How to derive offsets ?

### ISSUE THREAD

**Issue by sandiz** [kokolihapihvi/RockSnifferLib#2]
Hi @kokolihapihvi, awesome work on the project! 😃 

I am trying to port rocksnifferlib to [mac os](https://github.com/sandiz/RockSnifferLib/tree/mac). So far I have mac api's working, next step would be to find the correct memory address to read the song id/timer data etc.

How did you find the values for the pointers and the offsets ? 
(from [RSMemoryReader.cs](https://github.com/kokolihapihvi/RockSnifferLib/commit/5e6f9a1827b7465294251a36fa73f05d6d30e397#diff-48d48adbec9bdbc8f03324517bdbc376R46))
```
 byte[] bytes = MemoryHelper.ReadBytesFromMemory(rsProcessHandle, 
FollowPointers(0x00F5C494, new int[] { 0xBC, 0x0 }), 128);
```
I have been using CheatEngine on mac to search for "Play_SONGID_Preview" and working backwards to get a valid pointer but so far i have had no success. The same procedure works on windows and i get to the same pointer/offset value that you found. Curious to know if you have a different process ?

**Comment by kokolihapihvi** [comment]
Hey!

I used Cheat Engine to find all the pointers, for the song id one I had to scan for the "Play_SONGID_Preview" address to find the 0-offset address first, and then pointer scan for that address.

I don't know how the mac version of the game differs from the windows version, but I would try the CE pointer scanner.

Good luck!

**Comment by sandiz** [comment]
Hi @kokolihapihvi 

your pointers earlier worked and i was able to find song id and song timer pointers. i am now having issues finding the pointer chain for song note data. how did you search for those ?

sorry for reopening the issue, thanks for all the help!

**Comment by kokolihapihvi** [comment]
Hey,

I found those by starting a song, pausing at the start, scanning for 0 (4 bytes), playing a few notes and looking for increased values, and repeating a few times until I found the note counters.
After that I did the regular pointer scan routine to get the pointer paths.

**Comment by sandiz** [comment]
thanks for the info!

**Comment by sandiz** [comment]
hi @kokolihapihvi,
i have a macOS port working in my fork. Are you accepting Pull Requests to RockSniffer atm ?

thanks for writing such an awesome tool!

**Comment by kokolihapihvi** [comment]
Hey

I am accepting pull requests.
I've created a branch `macos` that you can PR against.

**Comment by sandiz** [comment]
thanks, i'll cleanup  my code and create a pr soon
