### ISSUE TITLE
Reading current path in Learn A Song

### ISSUE THREAD

**Issue by Farami** [kokolihapihvi/RockSnifferLib#6]
Hi there,

according to RSMemoryReader.cs the current path is at offset 01D0 in Score Attack:
`//01D0 - current path ("Lead"/"Rhythm"/"Bass")`

Unfortunately the current path offset is missing from your Learn A Song offset comment block.
Is it not possible to read the current path in Learn A Song?

**Comment by kokolihapihvi** [comment]
Hey,

I haven't found that in the learn a song structures, it might exist in some form though.
Ideally we'd want the selected arrangement instead of just the path, that'd open up some possibilities.

**Comment by Farami** [comment]
I’ll see if I can dig up something.

**Comment by kokolihapihvi** [comment]
https://github.com/kokolihapihvi/RockSnifferLib/commit/db81e4b47ce31f7ab798411a728097735027ad48 
Should be able to get arrangement id on learn a song, you can use this to reference the arrangements array to get the name of the arrangement (which will be Lead/Rhythm/etc). Seems like the arrangement id only exists in memory during songs.
